import {
  IconBaby,
  IconBag,
  IconBeauty,
  IconDiamond,
  IconElectro,
  IconEnergy,
  IconEquipement,
  IconGame,
  IconGift,
  IconHome,
  IconLeaf,
  IconMachine,
  IconMeuble,
  IconMode,
  IconPackaging,
  IconPhone,
  IconPieces,
  IconSport,
  IconTech,
  IconTools,
  IconVehicule,
} from "@/components/common/Icons";

export const categories = [
  { id: 1, name: "Santé et beauté", icon: <IconBeauty /> },
  { id: 2, name: "Informatique", icon: <IconTech /> },
  { id: 3, name: "Électroménager", icon: <IconElectro /> },
  { id: 4, name: "Maison Et Bureau", icon: <IconHome /> },
  { id: 5, name: "Articles Sports", icon: <IconSport /> },
  { id: 6, name: "Jeux et consoles", icon: <IconGame /> },
  { id: 7, name: "Mode", icon: <IconMode /> },
  { id: 8, name: "Produits pour bébé", icon: <IconBaby /> },
  { id: 9, name: "Téléphones et tablettes", icon: <IconPhone /> },
  { id: 10, name: "Outils et quincaillerie", icon: <IconTools /> },
  { id: 11, name: "Meubles", icon: <IconMeuble /> },
  { id: 12, name: "Environnement", icon: <IconLeaf /> },
  { id: 13, name: "Machine industrielle", icon: <IconMachine /> },
  { id: 14, name: "Emballage et impression", icon: <IconPackaging /> },
  { id: 15, name: "Bijoux, Lunettes Montres", icon: <IconDiamond /> },
  { id: 16, name: "Pièces Automobiles", icon: <IconPieces /> },
  { id: 17, name: "Bagages, sacs", icon: <IconBag /> },
  { id: 18, name: "Véhicule et transport", icon: <IconVehicule /> },
  { id: 19, name: "Équipement de services", icon: <IconEquipement /> },
  { id: 20, name: "Cadeaux et artisanat", icon: <IconGift /> },
  { id: 21, name: "Énergie renouvelable", icon: <IconEnergy /> },
];
